web/feat: cleaning & seo
ZeroMolecule/screenary pull request #1
Opened 2023-10-20 10:52 UTC by im-luka

[SCREEN - 22 ➡️ Setup Favicon and SEO Metadata](https://zeromolecule.atlassian.net/browse/SCREEN-22?atlOrigin=eyJpIjoiYjJlZDdkODE3Y2VmNGJhZmFmNDdmMmRmNWEzY2EzNzMiLCJwIjoiaiJ9)  
- [Add Favicon and Configure SEO Metadata](https://zeromolecule.atlassian.net/browse/SCREEN-34?atlOrigin=eyJpIjoiMDg5NDBlM2I5ZTVmNDQ4ZTk4NmVhY2I2MDNkMmMwNjgiLCJwIjoiaiJ9)

2023-10-20 13:06 UTC, im-luka commented on packages/web/app/layout.tsx
> +export const metadata: Metadata = {
nisam još dodao translacije, to je samostalni task (idući na redu)

2023-10-20 13:06 UTC, im-luka commented on packages/web/app/layout.tsx
> +  metadataBase: new URL(process.env.WEB_URL as string),
ok, pogledam kako to ide

2023-10-20 13:09 UTC, kjurenec commented on packages/web/app/layout.tsx
> +export const metadata: Metadata = {
sad smo s time napraviti tehnicki dug. al ok nije veliki pa napraviti onda translacije al nemoj zaboraviit na ovo

2023-10-24 07:02 UTC, kjurenec requested changes

2023-10-24 07:02 UTC, kjurenec commented on packages/web/env.ts
> +const envParsed = envSchema.safeParse(process.env);
koristi moza bolje parse koji throwa. pa onda neces morati tucno logati i throwati.
ako koristis vec safeParse onda mores kroz throw prikazati err u konzoli bez da moras i console.err koristiti.

2023-10-24 11:06 UTC, kjurenec requested changes

2023-10-24 11:06 UTC, kjurenec commented on packages/web/env.ts
> +const envParsed = envSchema.parse(process.env);
mogao si odma ovo `export ENV` :)

2023-10-24 11:06 UTC, kjurenec approved these changes

2023-10-24 11:48 UTC, merged