web/api/feat: profile (me) update & delete
ZeroMolecule/screenary pull request #10
Opened 2023-11-03 11:54 UTC by im-luka

[SCREEN - 49 ➡️ Profile Editing](https://zeromolecule.atlassian.net/browse/SCREEN-49?atlOrigin=eyJpIjoiN2RiN2UxYjA3ZDFkNDI1MWI5NzFmZGYzNTExZGQ5MzAiLCJwIjoiaiJ9)
- [[Frontend] Implement Profile Editing Screen](https://zeromolecule.atlassian.net/browse/SCREEN-51?atlOrigin=eyJpIjoiNDVhMzU2NzI4YzcxNDVlNWFiYzA2YTIyOWRhN2QzNTMiLCJwIjoiaiJ9)
- [[Backend] Implement Profile Editing API](https://zeromolecule.atlassian.net/browse/SCREEN-50?atlOrigin=eyJpIjoiMWM2OGEzYmJmNTdkNGE4NDg3OTgwZTVhZTdmNjE3ODgiLCJwIjoiaiJ9)

[SCREEN - 53 ➡️ Profile Deletion](https://zeromolecule.atlassian.net/browse/SCREEN-53?atlOrigin=eyJpIjoiNDFiOGE4OWUwNTEzNGQyNTlmYjRjM2JhNmM4ZWVjNjAiLCJwIjoiaiJ9)
- [[Frontend] Implement Profile Deletion Option](https://zeromolecule.atlassian.net/browse/SCREEN-55?atlOrigin=eyJpIjoiYjdhYTFjZGU5MWQ5NDMyYTg0MDcxMjA4YzRmOGFjOWIiLCJwIjoiaiJ9)
- [[Backend] Implement Profile Deletion API](https://zeromolecule.atlassian.net/browse/SCREEN-54?atlOrigin=eyJpIjoiZGJiZDc1MTc0N2Q3NDU5ZmIxMDdlOTkyMWJiNjliNzgiLCJwIjoiaiJ9)

2023-11-06 15:00 UTC, kjurenec requested changes

2023-11-06 20:34 UTC, im-luka commented on packages/web/app/_components/modals/profile-modal.tsx
> +        deleteModalBody
krenuo sam tim načinom i onda se prebacio da bude jedan modal jer mi se činilo dosta bolje rješenje s obzirom da je dio za deletanje usko vezano uz ovaj prvi modal (na taj dio se nikada ne može doći direktno osim putem editing modala) pa je po meni nepotrebna tranzicija otvaranja novog modala i zatvaranja starog (a i uzelo bi više vremena za implementaciju), ali ok budem promijenio i napravio tako

2023-11-06 20:35 UTC, im-luka commented on packages/web/app/[locale]/()/page.tsx
> +  const onEdit = useNotificationSuccess('saved');
može dodati ću globalno, ali ću u ovom slučaju svejedno morati pozvati notification success metodu s obzirom da se u onSuccess metodi useMutationa treba još pozvati nekoliko drugih metoda (update sesije, zatvaranje modala) pa će svakako overrideati ono što je setupirano kao default opcija kod inicijalizacije queryClienta

2023-11-06 20:49 UTC, im-luka commented on packages/web/next.config.js
> +    remotePatterns: [{ hostname: 'lh3.googleusercontent.com' }],
u tom slučaju će se u listu trebati dodati i taj drugi provider koji se koristi, to je radi sigurnosti da se ne mogu slike od bilokud serveati u appu. ne znam koje providere priznaje out-of-the-box a koje ne, ali znam da sam za google i za github uvijek morao dodati domenu kada sam radio social auth 

https://nextjs.org/docs/messages/next-image-unconfigured-host
https://nextjs.org/docs/app/api-reference/components/image#remotepatterns

<img width="741" alt="Screenshot 2023-11-06 at 21 43 40" src="https://github.com/ZeroMolecule/screenary/assets/46372998/30bce587-9eb6-4150-b689-54c244282b9f">

2023-11-06 20:53 UTC, im-luka commented on packages/web/app/_components/modals/profile-modal.tsx
> +  user?: Partial<User>;
ako maknem "?" check, baca error jer useSession hooka za usera može vratiti da ne postoji, a iz sesije se šalju user podatci u profile formu unutar modala

2023-11-07 08:24 UTC, kjurenec commented on packages/web/next.config.js
> +    remotePatterns: [{ hostname: 'lh3.googleusercontent.com' }],
ok cini se super kao extra security

2023-11-07 08:24 UTC, kjurenec commented on packages/web/app/_components/modals/profile-modal.tsx
> +  user?: Partial<User>;
mislio sam na Partial dio

2023-11-07 08:26 UTC, kjurenec commented on packages/web/app/_components/modals/profile-modal.tsx
> +        deleteModalBody
i dalje bi to bilo sve u ProfileModal cmp tako da cmp koje koriste profile modal i dalje salju iste propove samo sto se unutarnji kod mijenja. al sad nemamo bas vremena pa ce ovo biti ok

2023-11-07 08:38 UTC, kjurenec requested changes

2023-11-07 08:38 UTC, kjurenec commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
ovo ti treba? ko primjera je to bilo zbog height i width al obzirom da sam rekao da to ne treba ono je ovo suvisno. ista stvar i za loading. znaci koristi nativni loading.
"makni samo ovo sa visinia/sirina. nek samo mijenja loading prop." 

jesi testirao kad proimise crasha?

2023-11-07 08:38 UTC, kjurenec commented on packages/web/app/[locale]/()/page.tsx
> +  const onEdit = useNotificationSuccess('saved');
ok ima smisla

2023-11-07 12:49 UTC, im-luka commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
iskreno nisam ni shvatio poantu ovog buttona, ali sam zbog manjka vremena dodao kada si mi rekao. kad promise crasha se raspadne, ne razumijem najbolje razlog i logiku jer se prije to nije događalo kad je bio običan button

2023-11-07 12:49 UTC, im-luka commented on packages/web/app/_components/modals/profile-modal.tsx
> +  user?: Partial<User>;
a zato jer session user ima samo fieldove name, email, image a prismin user ima uz to još nekoliko fieldova. promijenio sam da type bude SessionUser a ne prismin

2023-11-07 13:00 UTC, kjurenec commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
poanta je da ne moras raditi prop drilling samo za isLoading a samo koristis u buttonu to. pa onda ako onClick bude promise automatski button zna jel treba loading ili ne

2023-11-07 13:01 UTC, kjurenec commented on packages/web/app/_components/modals/profile-modal.tsx
> +  user?: Partial<User>;
ok za sad ima smisla. mores ti prisma usera utrpati u session isto al otom potom

2023-11-07 13:10 UTC, kjurenec commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
zast se raspada jer jer se throwa error koji nije nista drugacije nego obicni sync error

2023-11-07 13:16 UTC, im-luka commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
kako ti onda handleas na prospetctoryju taj dio kad se promise raspadne?

2023-11-07 13:21 UTC, kjurenec commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
catch :)

2023-11-07 13:34 UTC, im-luka commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
iskreno ne razumijem te i već sam iskreno dosta burnoutan od ovih pr-ova. na koji catch misliš?

2023-11-07 13:35 UTC, im-luka commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
ne nalazim rješenje, bacim error a izvrši se dio unutar onSuccess funkcije useMutationa koji se ne bi smio izvršit

2023-11-07 13:35 UTC, im-luka commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
u prospectoryju ne nalazim dio gdje ti handleas potencijalni promise error

2023-11-07 13:50 UTC, kjurenec commented on packages/web/app/_components/base/button.tsx
> +  const elRef = useRef<HTMLButtonElement>(null);
mutateAsync od useMutation je async fnc koja more crashati (ima smisla?) sto znaci da tamo gdje pozivas tu funkciju napravis .catch(()=>null) to je najjednostavnije rjesenje

2023-11-07 14:19 UTC, merged