web/feat: projects list & screensaver home screens
ZeroMolecule/screenary pull request #14
Opened 2023-11-09 13:27 UTC by im-luka

[SCREEN - 4 ➡️ HOME SCREEN](https://zeromolecule.atlassian.net/browse/SCREEN-4?atlOrigin=eyJpIjoiMGRmNTE2ZGNmNDkzNGQyMmIzMjRhNzc1Y2Q5NzE3MTAiLCJwIjoiaiJ9)
- [Header Navigation](https://zeromolecule.atlassian.net/browse/SCREEN-63?atlOrigin=eyJpIjoiMTc3MWVmOTVhYTNiNDdlM2FmZDJkMDg0NzgyYWU1ZTMiLCJwIjoiaiJ9)
- [User Profile Widget in Header](https://zeromolecule.atlassian.net/browse/SCREEN-64?atlOrigin=eyJpIjoiY2MwNDlhYjRhZjQxNGZkZGI1ZGM0M2MxMWI0ZDA5YzUiLCJwIjoiaiJ9)
- [Project Listing on Home Screen](https://zeromolecule.atlassian.net/browse/SCREEN-65?atlOrigin=eyJpIjoiZDY1ZGVkMjY5YWQxNDAxZTk1MGM0OGQxNmVkODQyYzYiLCJwIjoiaiJ9)
- [Hovering Info Bar with Time and Greeting](https://zeromolecule.atlassian.net/browse/SCREEN-66?atlOrigin=eyJpIjoiZWY4NTdiZGRlM2I0NDhiYzk0OGEyNTdkODM5ZTk4MzMiLCJwIjoiaiJ9)

2023-11-09 15:35 UTC, kjurenec requested changes
pricali smo da notif nece biti pa makni. kad bilo gdje kliknes ode na /projects
![Uploading CleanShot 2023-11-09 at 15.37.13.png…]()

cudno ponasanje bg projekta
https://github.com/ZeroMolecule/screenary/assets/9319312/7aa773af-b17e-4bd9-abe5-e8b86400e0ec

notif cijeli makni obizrom da toga nece biti
![CleanShot 2023-11-09 at 15 39 13](https://github.com/ZeroMolecule/screenary/assets/9319312/8386041f-ba42-4ff1-a1b1-feb624f5e709)

2023-11-09 15:35 UTC, kjurenec commented on packages/web/hooks/use-live-clock.ts
> +  return { currentDateTime, formatter };
mislim da je jednostavnije samo date imati za ime var jer vec po imenu hook se kuzi sto je

2023-11-09 15:35 UTC, kjurenec commented on packages/web/hooks/use-live-clock.ts
> +  const [currentDateTime, setCurrentDateTime] = useState(new Date());
vidi jel ok new Date() koristiti u nextu. znam da su se ljudi zalili na to. kao zbog cachiranja date se ne updata.  (moze biti da samo u produ je tako)
obzirom da kod nas imamo useEffect samo inicijalno ce biti krivo.

2023-11-09 15:35 UTC, kjurenec commented on packages/web/utils/datetime.ts
> +  default: '',
hmmm? nisam siguran da default ima smisla

2023-11-09 15:35 UTC, kjurenec commented on packages/web/styles/utilities.css
> +.flex-1 {
utils folder bi trebao biti a onda flex file sa flex stvarima i overflow file s overflow stvarima. da ne mijesamo kruske i jabuke

2023-11-09 15:35 UTC, kjurenec commented on packages/web/styles/components/notifications-widget.css
cek jel to sad css file ili scss? vidim da code highlighter ne radi ovako

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/_components/user-widget/user-menu.tsx
> +      }, 175);
prilicno specifican timeout?

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/_components/user-widget/user-menu.tsx
> +      onClick: async () => await signOut(),
ne treba await

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/_components/user-widget/user-menu.tsx
> +  const controlRef = useRef<HTMLButtonElement | null>(null);
trebamo ovo?

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/_components/user-widget/user-menu.tsx
> +      pos="absolute"
mislim da apsolute ne treba? samo cemo imati problema kad ce trebatiti resize raditi za responsive

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/[locale]/()/(pages)/projects/page.tsx
> +    <Box h="100%">
ovaj box ima smisla da je u projects wrapperu isto. ime project wrapper mi je cudno obzirom da nije wrapper wec zapravo page.
 wrapper vise govori da wrappas nesto u nesto a toj wrapper niti ne prima children

2023-11-09 15:35 UTC, kjurenec commented on packages/web/styles/components/projects.css
> +    width: calc(33% - 7.65px);
ne vidim zasto nisi gird koristio. 
drugi put kad imas brojeve 7.65 zaokruzi na blizi parni

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/_components/header/navigation-link.tsx
> +export type NavigationLink = Props;
prop sufix bi trebao ovdje

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/[locale]/()/page.tsx
> +            textProps={{ fz: 24, lh: '28px', c: 'neutral.3' }}
lh mora ovisiti o font sizeu

2023-11-09 15:35 UTC, kjurenec commented on packages/web/app/_components/providers/theme/other.ts
> +  glassColor: '#17140BE5',
rade razdvoji color i alpha da je citljivije

2023-11-09 15:39 UTC, kjurenec requested changes

2023-11-09 15:39 UTC, kjurenec commented on packages/web/messages/en.json
> +    "welcomeMessage": "Good afternoon, {username}",
cek uvijek ce biti isto? nece ovisiti o dobu dana?

2023-11-10 10:19 UTC, im-luka commented on packages/web/app/_components/projects/projects-wrapper.tsx
> +    <div key={id} className="project-item-wrapper">
taj dio sam u idućem tasku prelomio na manje dijelove, ali c/p ću isto ovdje

2023-11-10 12:04 UTC, im-luka commented on packages/web/styles/components/notifications-widget.css
za kaj me točno pitaš? obični su .css fileovi ali ima support npr za ovaj identing kao što .scss ima

2023-11-10 12:04 UTC, im-luka commented on packages/web/app/_components/user-widget/user-menu.tsx
> +      }, 175);
ljepše mi je izgledala animacija, ali staviti ću 200ms koliko parent animacija traje 🙂

2023-11-10 12:15 UTC, im-luka commented on packages/web/app/_components/user-widget/user-menu.tsx
> +  const controlRef = useRef<HTMLButtonElement | null>(null);
stvarno ne znam kaj se promijenilo otkako sam jučer radio na ovome, ali bez ovog mi je panel uvijek imao width koji ne odgovara controlu. a sad normalno radi bez tog. hmm

2023-11-10 12:21 UTC, im-luka commented on packages/web/app/_components/user-widget/user-menu.tsx
> +      pos="absolute"
bez absolutea dolazi do ovog:
https://github.com/ZeroMolecule/screenary/assets/46372998/4b5c3de5-da1f-49ad-b9a3-b3315b4d8369

mogu jedino fixat da stavim neki div iznad toga kao parent, ako je to bolje. npr ovako:
![image](https://github.com/ZeroMolecule/screenary/assets/46372998/342c7083-cabd-40d6-982e-bceb216cff2b)

2023-11-10 12:32 UTC, kjurenec requested changes

2023-11-10 12:32 UTC, kjurenec commented on packages/web/styles/components/notifications-widget.css
prebaci u scss pa da ti code completer/highlighter radi kak treba. vidis po bojama da nekaj nestima

2023-11-10 12:45 UTC, im-luka commented on packages/web/app/[locale]/()/page.tsx
> +            textProps={{ fz: 24, lh: '28px', c: 'neutral.3' }}
gledam po dizajnu, u tipografiji su definirani line-heightovi za svaku veličinu, osim za neke random slučajeve kao što je ovaj. u dizajnu je u ovom slučaju za text stavljen line-height od 28px, a za title normal (height samog titlea iznosi 97px pa sam zato zaokružio na 100px). na koji način mora ovisi u ovom slučaju? kalkulacijom ili? s obzirom da ili nije definirano u dizajnu ili je hardkodirano

2023-11-10 13:08 UTC, im-luka commented on packages/web/styles/components/projects.css
> +    width: calc(33% - 7.65px);
zato jer sam mislio da je poanta layouta da uvijek budu 2 rowa, a kroz grid to ne mogu definirat osim da grid-columnu (project-itemu) dajem fixan height (npr. 300px). ne mogu to napraviti kroz postotak (npr. 50%), pa da automatski bude prilagođeno za nekoliko veličina ekrana bez da moram ručno mijenjati vrijednost. ili mogu ali nisam našao rješenje?

2023-11-10 13:32 UTC, kjurenec commented on packages/web/styles/components/projects.css
> +    width: calc(33% - 7.65px);
hmm. znaci zelis prikazati 6 itema. 3 po rowu. 2  po koloni. to je 2d polje zbog ceka i grid postoji.
mores lako to napraviti definirajuci samo 3 po rowu pa ce ovaj automatski preci u drugi red. obzirom da ces kroz paginaciju definirati koliko itema dohvacas po pageu (stavit ces 6 poslje) imat ces 2 kolone

2023-11-10 13:33 UTC, kjurenec commented on packages/web/styles/components/projects.css
> +    width: calc(33% - 7.65px);
visina ide automatski koliko sam item uzima

2023-11-10 13:34 UTC, kjurenec commented on packages/web/app/[locale]/()/page.tsx
> +            textProps={{ fz: 24, lh: '28px', c: 'neutral.3' }}
broj bez mjerne jedinice ili %. px nikad  nismo za lineheight koristili

2023-11-10 13:53 UTC, kjurenec commented on packages/web/app/_components/user-widget/user-menu.tsx
> +      pos="absolute"
aa kuzim. mozda smo mogli Menu cmp koristit onda al ok neka ostane ovako onda

2023-11-10 15:05 UTC, im-luka commented on packages/web/styles/components/projects.css
> +    width: calc(33% - 7.65px);
da, taj dio je jednostavan. ali kaj nije poanta tog projects-wrappera da ukoliko se dohvati više od 6 itema (koji istovremeno mogu biti prisutni u screenu), cijela ta sekcija treba postati scrollabilna. parent ima overflow na auto i onda se ovaj dio scrolla. i dalje je uvijek pristuno max 6, ali se može scrollati pa ih dolje još ima. a to znači da moram definirati height jer u slučaju da ima više od 6 itema, cijela ta sekcija će se stisnuti i biti će neki drugi broj itema a ne 6 (bez heighta na project-itemu)

2023-11-13 08:42 UTC, kjurenec requested changes
@im-luka maknes cl ovaj neki
![CleanShot 2023-11-13 at 09 39 10](https://github.com/ZeroMolecule/screenary/assets/9319312/4cb84473-549d-4317-9b8a-8378cf908be2)

i dalje problem s ovim gore na projektima
https://github.com/ZeroMolecule/screenary/assets/9319312/616fb76f-00a0-446a-ac3c-fad81ac3952d

2023-11-13 09:02 UTC, kjurenec requested changes

2023-11-13 09:11 UTC, im-luka commented
> @im-luka maknes cl ovaj neki ![CleanShot 2023-11-13 at 09 39 10](https://user-images.githubusercontent.com/9319312/282406073-4cb84473-549d-4317-9b8a-8378cf908be2.png)
> 
> i dalje problem s ovim gore na projektima https://github.com/ZeroMolecule/screenary/assets/9319312/616fb76f-00a0-446a-ac3c-fad81ac3952d

gdje si našao ovaj console.log i jesi siguran da je moj? 😅

![Screenshot 2023-11-13 at 09 47 19](https://github.com/ZeroMolecule/screenary/assets/46372998/bd3ee268-ee04-43bf-ab42-064df70dc99c)
<img width="1403" alt="Screenshot 2023-11-13 at 09 47 53" src="https://github.com/ZeroMolecule/screenary/assets/46372998/dce4ad22-2747-49d9-b7e2-9538b9dcb353">

jel imaš ideju kako riješiti ovaj problem sa bg na project-itemu bez pisanja velikog broja media-queryja?
![image](https://github.com/ZeroMolecule/screenary/assets/46372998/7de74691-5d5d-4e41-a213-10e51839c577)

2023-11-13 09:57 UTC, kjurenec approved these changes

2023-11-13 09:57 UTC, merged