web/feat: google calendar
ZeroMolecule/screenary pull request #18
Opened 2023-11-15 13:00 UTC by im-luka

Calendar Page

2023-11-16 08:41 UTC, kjurenec requested changes
u dizajnu nema ovog paddinga od kartice?
![CleanShot 2023-11-16 at 09 40 46](https://github.com/ZeroMolecule/screenary/assets/9319312/e6e60626-5f34-475a-a5fb-728a197e35d4)

malo je cudno imati 2 scrolla u ovom slucaju
![CleanShot 2023-11-16 at 09 41 10](https://github.com/ZeroMolecule/screenary/assets/9319312/63272b49-90f6-4cc9-ad8e-47fc26f382a9)

2023-11-16 08:41 UTC, kjurenec commented on packages/web/app/_components/providers/theme/components.ts
> +    classNames: {
zast style imamo malo ko gore kroz objekt a malo kroz scss klase?

2023-11-16 08:47 UTC, kjurenec commented on packages/web/app/_components/projects-tabs.tsx
> +export const ProjectsTabs: FC<Props> = ({ defaultTab, tabs, onChange }) => {
e mozda bolje koristiti https://mantine.dev/core/segmented-control/ da budu ove tranzicije :) ?

2023-11-16 08:52 UTC, kjurenec requested changes

2023-11-16 08:52 UTC, kjurenec commented on packages/web/hooks/use-projects-tabs.ts
> +export const useProjectsTabs = () => {
ovo ce trebati prepraviti.
obizorm na sto user klikne u tabu url se mora mijenjati. ovako kad refresha page otici ce na prvi projekt.
drugo ne izvaclis project is projects jer projects je paginiran pa ne znaci da ce biti prisutan u njemu.
saljes req na specificni projekt

2023-11-16 20:04 UTC, im-luka commented
> u dizajnu nema ovog paddinga od kartice? ![CleanShot 2023-11-16 at 09 40 46](https://user-images.githubusercontent.com/9319312/283373240-e6e60626-5f34-475a-a5fb-728a197e35d4.png)
> 
> malo je cudno imati 2 scrolla u ovom slucaju ![CleanShot 2023-11-16 at 09 41 10](https://user-images.githubusercontent.com/9319312/283373377-63272b49-90f6-4cc9-ad8e-47fc26f382a9.png)

što se tiče paddinga - rekao bih da je u dizajnu greška jer svi ostali cardovi takve veličine (npr. calendar koji nije google, to-do lista i taskovi, mail tj inbox card) imaju mali padding i border radius. u ovom slučaju mi se čini da je screenshot google calendara loše nalijepljen (gore desno na screenshotu se vidi da je jedan dio loše odrezan). zato sam stavio border radius i padding kao što je i svugdje drugdje (zbog konzistentnosti), ali ako misliš da to nije ispravno mogu promijeniti ili vidjeti s dizajnom

što se tiče ovog duplog scrolla - jesi imao taj problem i kod calendara ili samo ovako kod linkova kao što su next.js dokumentacija koji si stavio (a zapravo tu ne bi trebao ići)? provjerio sam taj dio i kod calendara nikada nisam imao taj problem, samo kod nekih pageva kao što su dokumentacije. a razlog zašto sam stavio min-height na iframe je jer bez fixnog min-heightea, tj. samo s heightom od 100% će calendar ovako izgledati na screenovima kao što je np. mac 13':
<img width="1440" alt="Screenshot 2023-11-16 at 21 01 38" src="https://github.com/ZeroMolecule/screenary/assets/46372998/c040afb8-355d-4a5f-9b2a-faf602de76ac">
činilo mi se dosta stisnuto sve, ali ako je to ok ostavim tako

2023-11-16 20:06 UTC, im-luka commented on packages/web/app/_components/providers/theme/components.ts
> +    classNames: {
obično sve radim kroz styles (dokle se god može raditi kroz styles). u ovom slučaju kod tabbova sam morao manipulirati `data-[*]` atributima, a taj dio se ne može napraviti kroz styles (ili može?) pa sam zbog toga morao dodati i klase

2023-11-17 08:04 UTC, kjurenec commented on packages/web/app/_components/providers/theme/components.ts
> +    classNames: {
nez probaj. ako neide ok.
meni je samo bilo cudno sto mijesamo al ako je validno nema problema.

2023-11-17 08:16 UTC, kjurenec commented
@im-luka sto se tice paddinga. sve ovisi o kontekstu. nije bit da je svugdje isto ako nema smisla. tipa kod todo liste ima smisla jer oces malo sapcinga da se itemi odvoje od rubova kartice. al recimo ako imamo iframe onda ce. full sirine/visine kartice je ce biti ljepse (kak je i u dizajnu ko mail iframea). sto se tice ovo sirine vidi s dizajnom. sam google calendar nema scroll bara al tam ima vise mjesta pa nije problem.

2023-11-17 08:18 UTC, kjurenec commented
inace sve sto nisi 100% siguran bilo dizajn bilo logika u kodu pitaj u chatu. bolje to tamo raspraviti neko fiksati naknadno pr

2023-11-17 08:20 UTC, im-luka commented on packages/web/app/_components/projects-tabs.tsx
> +export const ProjectsTabs: FC<Props> = ({ defaultTab, tabs, onChange }) => {
probao sam koristiti segmented control, ali ne znam jesi li gledao kako izgleda dom tree kod te komponente. uopće nije dobro strukturirano i nisam uspio editirati na razini teme, a uzelo mi je dosta vremena. pa sam stavio tabse, a ovaj dio bi rađe ostavio za polishing fazu (za animaciju bi čak rađe koristio framer-motion jer mislim da bi bilo lakše)

2023-11-17 08:23 UTC, kjurenec commented on packages/web/app/_components/projects-tabs.tsx
> +export const ProjectsTabs: FC<Props> = ({ defaultTab, tabs, onChange }) => {
hmm na prospectoriju mi se nije cinilo tako kompleksno kad sam to radio. reko bi da framer-motion nema potrebe jer vec mantine ima tranzicije za to pa je malo redundantno.

2023-11-17 08:23 UTC, kjurenec commented on packages/web/app/_components/projects-tabs.tsx
> +export const ProjectsTabs: FC<Props> = ({ defaultTab, tabs, onChange }) => {
al ok neka bude sad ovako

2023-11-17 13:21 UTC, kjurenec commented on packages/web/hooks/use-projects-tabs.ts
> +        (p) => p.id === searchParams.get(PROJECT_TAB_PARAMS_KEY)
ovo si mogao staviti u varijablu iznad pa da ne moras 2x zvati get

2023-11-17 13:21 UTC, kjurenec commented on packages/web/hooks/use-projects-tabs.ts
> +  const searchParams = useSearchParams();
ispravniji nacin bi bilo da nije preko url querija vec url params (calendar/:id) obzirom da je project id required da funkcionira taj page. query koristis samo ako je nesto opcionalno.
al s pravim nacinom ces se morati zezati kako inicijalno postaviti id tako da je ovo sad ok.

2023-11-17 13:21 UTC, kjurenec commented on packages/web/hooks/use-projects-tabs.ts
> +  const searchParams = useSearchParams();
kak ti ja inace imam url query rijeseno je preko ovog hooka.
https://github.com/biyer/prospectory/blob/main/packages/web/app/_hooks/use-url-query.tsx

znaci on prima zod schemu i onda returna ono sto zod vrati preko validacije pa si onda siguran da je query param pravog tipa a ujedno imas i type postavljen. sad za ovo ne moras nista ai kasnije kad ces imati kompleksnije (arr ili objekt u queriju) stavari poput paginacije dobro dode.

ovako ga koristim 
```
const [query] = useUrlQuery(z.object({ code: z.string().nonempty() }));
const code = query?.code; //tocno znas kojeg je oblika/tipa query
```

2023-11-17 13:22 UTC, kjurenec approved these changes

2023-11-17 13:25 UTC, im-luka commented on packages/web/hooks/use-projects-tabs.ts
> +        (p) => p.id === searchParams.get(PROJECT_TAB_PARAMS_KEY)
doslovno sam par min razmišljao hoću li to napraviti ali na kraju nisam jer sam si mislio da mi ta varijabla treba samo za taj ternary operator pa kao zbog performancea da ne radi varijablu na svaki render 😅 (ako to uopće ugrožava performance)

2023-11-17 13:25 UTC, im-luka commented on packages/web/hooks/use-projects-tabs.ts
> +  const searchParams = useSearchParams();
super. zapisao sam si ovo pa napravim tako kasnije

2023-11-17 13:26 UTC, merged