web/feat: pwa setup
ZeroMolecule/screenary pull request #2
Opened 2023-10-20 13:03 UTC by im-luka

[SCREEN - 21 ➡️ Configure PWA](https://zeromolecule.atlassian.net/browse/SCREEN-21?atlOrigin=eyJpIjoiZTM4ZDE0YmVjODU1NDFlMDlhYWMwOTM5ZWU0OTFlOWMiLCJwIjoiaiJ9)
- [Configure the frontend project to be PWA, ensuring it meets all PWA criteria](https://zeromolecule.atlassian.net/browse/SCREEN-33?atlOrigin=eyJpIjoiNWI1M2Q4Zjk1MDZjNDViYTkzYjYyNjRkNjQ3ZTJkZWEiLCJwIjoiaiJ9)

2023-10-23 07:15 UTC, kjurenec requested changes

2023-10-23 07:15 UTC, kjurenec commented on packages/web/public/manifest.json
> +  "start_url": "http://localhost:4200/",
imas neki task/todo da ne zaboravis ovo updatati u pravi url? 
ili ima neki bilji nacin obzirom da ce ovo biti i lokalno i dev i prod?

2023-10-23 07:21 UTC, kjurenec commented
@im-luka nisam siguran al ovo od pwa je samo da mores dodati na desktop/screen pa da kad otvoris da nema browser controle? milim da pravi pwa ima i service worker za caching.

2023-10-23 10:18 UTC, im-luka commented on packages/web/public/manifest.json
> +  "start_url": "http://localhost:4200/",
puno sam istraživao kako ubaciti `process.env` varijablu unutar `manifest.json` filea i probao sam implementirati stvari koje su reportane u ovom conversationu (CopyPlugin dodan u webpack config) 👉🏼 https://github.com/facebook/create-react-app/issues/7953

ali mi rješenje ne radi dobro, u browseru unutar manifest filea ostane isti naziv varijable (ne updatea se vrijednost iz `process.env`). probao sam vidjet mogu li to napraviti kroz `instrumentation.ts` file, ali isto nisam uspio. ne znam postoji li rješenje za to, nisam pronašao ništa drugo. imaš ti ideju?

2023-10-23 10:58 UTC, im-luka commented
@kjurenec može malo više info toga? pratio sam next docse vezano uz manifest file. kad si napisao da misliš da treba dodati service worker za caching, trebam li to ručno napisati, ako da gdje bi išlo (kad se app starta, na serveru)? sad sam napravio konfiguraciju putem libraryja koji se navodno koristi za to 👉🏼 https://www.npmjs.com/package/next-pwa, ali ne znam je li sad sve ispravno i kako bih zapravo sve mogao testirati radi li (osim ikonice u browseru za preuzimanje appa, application taba u devtoolsu) pa pls mali help ako ti znaš

2023-10-24 07:05 UTC, kjurenec commented
> @kjurenec može malo više info toga? pratio sam next docse vezano uz manifest file. kad si napisao da misliš da treba dodati service worker za caching, trebam li to ručno napisati, ako da gdje bi išlo (kad se app starta, na serveru)? sad sam napravio konfiguraciju putem libraryja koji se navodno koristi za to 👉🏼 https://www.npmjs.com/package/next-pwa, ali ne znam je li sad sve ispravno i kako bih zapravo sve mogao testirati radi li (osim ikonice u browseru za preuzimanje appa, application taba u devtoolsu) pa pls mali help ako ti znaš

da koristi taj package. lako ti je testirati. samo odi iskljuci net i vidi dal loada assete iz cachea. 
imas u chromeu opcije kak da se worker ponasa u dev modu da mores testirati. napravi samo da service worker radi na produ (osim ako to lib vec nema)

2023-10-24 09:43 UTC, im-luka commented
[next-pwa](https://www.npmjs.com/package/next-pwa) library je dosta outdated i ne radi dobro sa next.js13. service workeri se ne registriraju dobro (tj. ne registriraju se uopće). za rješenje sam koristio 👉🏼 [github conversation](https://github.com/shadowwalker/next-pwa/issues/424). to ti stavljam ovdje kao referencu u slučaju da me pitaš što su ove stvari unutar `next.config.js` filea

2023-10-24 11:05 UTC, kjurenec commented
> [next-pwa](https://www.npmjs.com/package/next-pwa) library je dosta outdated i ne radi dobro sa next.js13. service workeri se ne registriraju dobro (tj. ne registriraju se uopće). za rješenje sam koristio 👉🏼 [github conversation](https://github.com/shadowwalker/next-pwa/issues/424). to ti stavljam ovdje kao referencu u slučaju da me pitaš što su ove stvari unutar `next.config.js` filea

moze se inace onda preko workboxa direkt al necemo onda to sad. mozemo kad rijesi ostale pa vise kao extra task

2023-10-24 11:05 UTC, kjurenec approved these changes

2023-10-24 12:01 UTC, merged