web/feat: notes
ZeroMolecule/screenary pull request #23
Opened 2023-11-16 14:15 UTC by im-luka

[Notes - List, Create, Edit, Delete](https://zeromolecule.atlassian.net/browse/SCREEN-7?atlOrigin=eyJpIjoiYzA2NGU1OTNiMDUzNDI5Njk1NjJkYzc3YzM0YjYxYjgiLCJwIjoiaiJ9)

nisam uopće pametan kako ove notese (ove zelene) prikazati. da li staviti fixan height&width, staviti min/max ili kako već. sto puta sam mijenjao, javi kako ti misliš da je najbolje

2023-11-16 15:45 UTC, kjurenec requested changes
i ovo bi trebalo biti clickabilno
![CleanShot 2023-11-16 at 16 22 53](https://github.com/ZeroMolecule/screenary/assets/9319312/12efcf47-2136-4ab1-af88-152cc87c6920)

ima smisla da te switcha na novi note
https://github.com/ZeroMolecule/screenary/assets/9319312/20024b8c-479f-42cf-aa4e-fae701857290

ovo bi trebalo biti ovelay. jednom kad dodas taskove onda ce "gurati" s njima a tak ne izgleda u figmi
![CleanShot 2023-11-16 at 16 34 34](https://github.com/ZeroMolecule/screenary/assets/9319312/9c9ca073-738c-495b-8f0d-edd1916b120a)

krive sirine je ovo
![CleanShot 2023-11-16 at 16 37 12](https://github.com/ZeroMolecule/screenary/assets/9319312/fbd5bd44-e3a4-47a5-a9a0-01c650acf5cc)

2023-11-16 15:45 UTC, kjurenec commented on packages/web/app/[locale]/()/(pages)/projects/[id]/page.tsx
> +      queryFn: () => notesQuery.fnc(id),
napravi i ovdje da je bez queryFn

2023-11-16 15:45 UTC, kjurenec commented on packages/web/app/_components/project/note.tsx
> +  if (!note) {
slobodno pitas u chatu za ovo

2023-11-16 15:45 UTC, kjurenec commented on packages/web/app/_components/project/note.tsx
> +        <textarea
ima mantine textarea cmp

2023-11-16 15:45 UTC, kjurenec commented on packages/web/app/_components/project/notes.tsx
> +    queryFn: () => notesQuery.fnc(projectId),
isto ko i u server varijanti

2023-11-16 15:45 UTC, kjurenec commented on packages/web/domain/types/note-data.ts
> +export type AddNoteData = Pick<Note, 'projectId'>;
mislim da je ovdje treba maknuti createdAt i updatedAt (vidi za ostale fieldove ako treba isto)

2023-11-17 13:32 UTC, kjurenec requested changes
ne updata se "selectani" note 

https://github.com/ZeroMolecule/screenary/assets/9319312/c616a848-7e33-4c8b-8eb2-5563f23dde11

2023-11-17 13:32 UTC, kjurenec commented on packages/web/domain/mutations/add-note-mutation.ts
> +      .post(`projects/${projectId}/notes`, { data: {} })
nema potrebe empty slati

2023-11-17 13:35 UTC, im-luka commented on packages/web/domain/mutations/add-note-mutation.ts
> +      .post(`projects/${projectId}/notes`, { data: {} })
a back očekuje data object. bez tog se raspadne

2023-11-17 13:51 UTC, kjurenec commented on packages/web/domain/mutations/add-note-mutation.ts
> +      .post(`projects/${projectId}/notes`, { data: {} })
ok onda ostavi svoje kak je al reci david da fiksa back onda

2023-11-17 13:54 UTC, im-luka commented
nisam siguran što je bolje staviti za key, možda bolje ovo drugo za svaki slučaj?

2023-11-17 13:56 UTC, kjurenec commented
> nisam siguran što je bolje staviti za key, možda bolje ovo drugo za svaki slučaj?

sad tek vidim. ni jedno. bez keya bi trebalo biti jer dosta smrdi ovako

2023-11-20 10:47 UTC, im-luka commented
request review @kjurenec

2023-11-20 10:48 UTC, kjurenec approved these changes

2023-11-20 10:48 UTC, merged