web/feat: tasks page
ZeroMolecule/screenary pull request #26
Opened 2023-11-28 12:43 UTC by im-luka

[Tasks Page](https://zeromolecule.atlassian.net/browse/SCREEN-9?atlOrigin=eyJpIjoiNjg2NmI1MTMxOTRkNDFhNmI5YzU5MDg0MTNmYjRiNTciLCJwIjoiaiJ9)

2023-11-28 15:56 UTC, kjurenec requested changes

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/task-item.tsx
> +      const value = inputRef.current?.value;
koristi value iz eventa. sto manje direkt domu pristupas u reactu to bolje

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/task-popover.tsx
> +                <FormDateInput
spoji date input i time input u svoju cmp tako da izvana kad bude recimo onChange bude Date arg.
isto kak mantine s default date time cmp ima.

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/task-item.tsx
> +  const formatDateMessage = useCallback(() => {
ovo ima vise smisla da je useMemo onda jer ne ovisi o ni jednom arg vec je samo memo value

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/task-item.tsx
> +        defaultChecked={isDone}
ima mi vise smisla da je checked umjesto default?
tako bolje kontroliras vrijednost.

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/task-item.tsx
> +          defaultValue={task.title}
ovdje je ocito malo kompleksija situacije nago u checkboxu. tak da neka ostane za sad

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/tasks-body.tsx
> +export const TasksBody: FC<Props> = (props) => {
malo cudno ime body za cmp?

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/tasks-page.tsx
> +  const { data, refetch } = useQuery<Data<Task[]>>({
ovaj query treba primati koje taskove obzirom na status treba fetchati.
sad imas loklano so znaci samo 25 todoa imas sve skupa jer nema paginacije pa da bar malo popravimo.

2023-11-28 15:56 UTC, kjurenec commented on packages/web/app/_components/tasks/task-popover.tsx
> +    <Stack
moda da koristimo mantine popover ili menu cmp? 
vec kad imamo ui lib ima mi smisla iskoristiti ga sto vise

2023-11-29 07:30 UTC, im-luka commented on packages/web/app/_components/tasks/task-item.tsx
> +      const value = inputRef.current?.value;
a u tom slučaju mi se typescript žali jer kaže da ne postoji `value` field kod typea `EventTarget`. a ako promijenim iz `KeyboardEvent` u `ChangeEvent` ili gore iz `onKeyDown` funkcije u `onChange` funkciju onda mi se žali da ne postoji `key` field na `e` objektu

2023-11-29 07:32 UTC, im-luka commented on packages/web/app/_components/tasks/task-item.tsx
> +      const value = inputRef.current?.value;
mogu uvijek stavit nešto tipa `const value = "value" in e.target && e.target.value;` ali ne znam je li to ispravno

2023-11-29 07:39 UTC, im-luka commented on packages/web/app/_components/tasks/task-item.tsx
> +        defaultChecked={isDone}
ali ni ne trebamo kontrolirat state? jer svaki `handleChange` je zapravo api call na edit pa nam je bitna samo default value? ovako moram imati još jedan state koji mi ni ne treba (ništa drugo ne ovisi o tome, osim što se odmah izvrši api endpoint na edit, a u slučaju api errora se vrijednost neće ni promijeniti nego će ostati ona defaultna da user ne bi mislio da je uspio promijeniti a zapravo se srušilo sve)

2023-11-29 07:47 UTC, im-luka commented on packages/web/app/_components/tasks/task-popover.tsx
> +    <Stack
i krenuo sam s tim, ali je bilo dosta custom stylinga wrappera i sl (slično kao onaj primjer s gridom) pa mi je zato bilo lakše napraviti samostalno. prebacim u popover onda

2023-11-29 07:56 UTC, im-luka commented on packages/web/app/_components/tasks/task-popover.tsx
> +                <FormDateInput
hmm na kaj točno misliš? mantine ima spojenu jedino [DateTimePicker komponentu](https://mantine.dev/dates/date-time-picker/), inače su `DateInput` i `TimeInput` odvojene komponente. a budući je u dizajnu to odvojeno nisam koristio `DateTimePicker` nego ovako odvojeno pa nisam najbolje skužio na kaj misliš

2023-11-29 09:24 UTC, kjurenec commented on packages/web/app/_components/tasks/task-popover.tsx
> +    <Stack
a samo container promijenis ono kaj je unutra je custom ko i kaj sad imas

2023-11-29 09:31 UTC, kjurenec commented on packages/web/app/_components/tasks/task-popover.tsx
> +                <FormDateInput
i dalje neces koristiti tu cmp al ces napraviti svoju koja ce kombinirati ovo sto si odvoje time i date napravio i onda ta cmp ce imati onChange(Date) da izvana izgleda kak treba a iznutra imas one vradzbine

2023-11-29 09:35 UTC, kjurenec commented on packages/web/app/_components/tasks/task-item.tsx
> +      const value = inputRef.current?.value;
`currentTarget` koristis

2023-11-29 10:51 UTC, im-luka commented on packages/web/app/_components/tasks/task-item.tsx
> +      const value = inputRef.current?.value;
da u pravu si, riješeno. iako kad napravim `console.log(e)` cijeli event mi `currentTarget` uvijek bude `null`, a kad napravim `console.log(e.currentTarget)` onda mi dobro ispiše `<input />` tag. zato sam mislio da je `currentTarget` null ali zapravo nije

2023-11-29 10:54 UTC, im-luka commented on packages/web/app/_components/tasks/task-popover.tsx
> +                <FormDateInput
aha na to misliš, ok mislim da kužim sve. napravim tako

2023-11-29 13:08 UTC, im-luka commented on packages/web/app/_components/tasks/task-item.tsx
> +        defaultChecked={isDone}
umjesto `defaultChecked` sam stavio `checked` i onda morao promijenit iz `onClick` u `onChange` (zbog errora u konzoli da nemam `onChange` a imam `value`). i to normalno radi,  ali je još jedna stvar kaj se izgubi ova animacija. u videu je prvi primjer sa `defaultChecked` a drugi sa `checked`

https://github.com/ZeroMolecule/screenary/assets/46372998/adfad7d3-4dbf-464d-af27-b975941efb50

2023-11-29 13:47 UTC, kjurenec commented on packages/web/app/_components/tasks/task-item.tsx
> +        defaultChecked={isDone}
aa kuzim jer se ceka response.  vrati onda  na staro sry :)

2023-11-29 13:51 UTC, im-luka commented on packages/web/app/_components/tasks/task-item.tsx
> +        defaultChecked={isDone}
np nije to ni bio moj glavni razlog nego sam isto skužio naknadno

2023-11-30 08:08 UTC, kjurenec requested changes

2023-11-30 08:08 UTC, kjurenec commented on packages/web/app/_components/base/form/date-time-input.tsx
> +        <TimeInput
sto ako iz hook-forma izvuce inicijalni value? date input bude bio ok al time input ce biti prazan

2023-11-30 08:10 UTC, kjurenec commented on packages/web/app/_components/base/form/date-time-input.tsx
> +        {t('label')}
label ide kroz prop jer je ovo genericki input

2023-11-30 14:49 UTC, kjurenec requested changes

2023-11-30 14:49 UTC, kjurenec commented on packages/web/app/_components/base/form/date-time-input.tsx
> +  const [time, setTime] = useState<string>(
ovo ce ti raditi samo za inicijalni  case.
sto ako value dolazi asyncrono iz hook forme?
znaci u pocetku je undefined | null i onda nakon par sekudni dode value (realni case u divljini), ili ides reset forme raditi

2023-12-01 08:07 UTC, kjurenec requested changes

2023-12-01 08:07 UTC, kjurenec commented on packages/web/app/_components/base/form/date-time-input.tsx
> +  useEffect(() => {
najgore sto mos napraivti je koristiti useEffect da updatas state kad se dependency promijeni

2023-12-01 08:07 UTC, kjurenec commented on packages/web/app/_components/base/form/date-time-input.tsx
> +  const [time, setTime] = useState<string>('');
i dalje inicijalno moras imati kak treba value.
na nacin kak sad imas je prvi render je empty pa tek onda na drugom renderu ti je kak treba

2023-12-01 11:38 UTC, im-luka commented on packages/web/app/_components/base/form/date-time-input.tsx
> +  useEffect(() => {
to onda znači da u parentu react-hook-form field i zod validacija više neće biti `dateTime` nego se treba odvojeno handleati `date` i `time` pa u tom slučaju ništa posebno nisam dobio s ovom komponentom? jer ne znam na koje rješenje ciljaš s obzirom da ova moja nisu dobra

2023-12-01 12:32 UTC, kjurenec commented on packages/web/app/_components/base/form/date-time-input.tsx
> +  useEffect(() => {
ili form.watch listener (u useEffectu ali u tom slucaju ne ovisis o dependeciju) ili ref (to je vjerojatno jednostavnije/bolje rjesenje)

2023-12-01 13:51 UTC, kjurenec approved these changes

2023-12-01 13:51 UTC, merged