web/feat: internationalization setup
ZeroMolecule/screenary pull request #3
Opened 2023-10-21 11:27 UTC by im-luka

[SCREEN - 61 ➡️ Configure Internationalization](https://zeromolecule.atlassian.net/browse/SCREEN-61?atlOrigin=eyJpIjoiY2Q0NjhiZDViNzU4NGMwNWJmY2Q3MmNhN2I3NmFhYmYiLCJwIjoiaiJ9)
- [Internationalization setup](https://zeromolecule.atlassian.net/browse/SCREEN-62?atlOrigin=eyJpIjoiNWU5MzBmMjk3YTI1NDlmN2I3ZTg4ZmRiOTkyMTJlMzkiLCJwIjoiaiJ9)

2023-10-23 07:10 UTC, kjurenec approved these changes

2023-10-23 07:10 UTC, kjurenec commented on package.json
> +    "next-intl": "^3.0.0-beta.19",
zakaj rc verziju ne koristimo?

2023-10-23 07:42 UTC, im-luka commented on package.json
> +    "next-intl": "^3.0.0-beta.19",
hmm support za server componente im je još u beti pa je tako u docsima:

<img width="1290" alt="Screenshot 2023-10-23 at 09 40 55" src="https://github.com/ZeroMolecule/screenary/assets/46372998/6f372a19-0f37-41a6-baea-8cbeb51417bc">

2023-10-24 07:11 UTC, kjurenec commented on package.json
> +    "next-intl": "^3.0.0-beta.19",
sad si me zbudio :). pa i koristis translacijeu u server cmp? mislim cijeli package v3 nije stable. al rc je zadnji korak prije  sable verzije za razliku od bete. probao si rc pa nije radilo? jednom kad stable izade imace manje prosla upgradati rc nego betu.

2023-10-24 07:52 UTC, im-luka commented on package.json
> +    "next-intl": "^3.0.0-beta.19",
koristim, zato i kažem. po docsima piše da su server componente još uvijek u beti te se zato koristi ova verzija. nisam probao bez nego sam ovako pratio docse, a koliko vidim i prospectory i dana-labs je koristio sličnu verziju također u beti

2023-10-24 11:08 UTC, kjurenec commented on package.json
> +    "next-intl": "^3.0.0-beta.19",
mislim da ti ta beta nije isto sto i beta o kojoj ti pricas.
kad su  prospectory i dana-labs kreirani nije bilo rc

2023-10-24 11:09 UTC, kjurenec commented on package.json
> +    "next-intl": "^3.0.0-beta.19",
probaj rc pa ako ne radi vratis

2023-10-24 13:31 UTC, im-luka commented
@kjurenec evo prebacio sam na 3.0 RC verziju. moram priznat da su puno toga promijenili, mentalni model je skroz drugačiji nego što je bio

prije su client componente bile službene, a server componente u beti, a sad su promijenili da je njihova preporuka da sve ide preko server componenti. da se doslovno translacije uvijek čitaju u server componentama, a u client componente koje ih trebaju - da ih prime preko propova. ima i primjera gdje se sve wrappa u `<NextIntlClientProvider />`, pa se u svim client componentama normalno koristi `useTranslation()` kao i prije, ali to ne preporučaju jer smanjuje performanse navodno 

ugl. tu su 👉🏼 [unofficial docsi](https://next-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app/docs/environments/server-client-components) gdje je sve objašnjeno. za sada sam wrappao sve u `<NextIntlClientProvider />` da ima support za client componente out-of-the-box, ali ti sve ovo pišem da uzmemo sve u obzir kak sad funkcionira pa da je lakše odlučiti kojim ćemo principom ići nadalje

2023-10-24 14:03 UTC, kjurenec requested changes

2023-10-24 14:03 UTC, kjurenec commented on packages/web/next.config.js
> +  webpack(config) {
ovo novo ili staro?

2023-10-24 14:10 UTC, im-luka commented on packages/web/next.config.js
> +  webpack(config) {
staro, to je ono od PWA brancha. povuklo je kada sam mergeao dev branch da riješim konflikte

2023-10-24 14:41 UTC, kjurenec requested changes

2023-10-24 14:41 UTC, kjurenec commented on packages/web/utils/datetime.ts
> +  Intl.DateTimeFormat().resolvedOptions().timeZone ?? DEFAULT_TIME_ZONE;
ovo cita timezone obzirom gdje se zove. recimo da je server u us onda ce biti us nesto a ti kao user dodes iz eu bude utc. kak se onda ponasati ovo? obzirom na server/client cmp.

2023-10-24 14:47 UTC, im-luka commented on packages/web/utils/datetime.ts
> +  Intl.DateTimeFormat().resolvedOptions().timeZone ?? DEFAULT_TIME_ZONE;
hmm ne razumijem. šta nije da ovo vadi timezoneu iz browsera s kojeg user pristupa pageu?

2023-10-24 15:00 UTC, kjurenec commented on packages/web/utils/datetime.ts
> +  Intl.DateTimeFormat().resolvedOptions().timeZone ?? DEFAULT_TIME_ZONE;
rekao si da se intl vrti i na serveru? a tam nema browsera

2023-10-25 07:05 UTC, kjurenec approved these changes

2023-10-25 07:06 UTC, merged