web/feat: embedded pages
ZeroMolecule/screenary pull request #35
Opened 2023-12-14 07:37 UTC by im-luka

[Embedded Pages](https://zeromolecule.atlassian.net/browse/SCREEN-11?atlOrigin=eyJpIjoiMWU5N2E5NzFkOTFiNDhlNGJmY2JhZTEzMGVlOGVhN2EiLCJwIjoiaiJ9)

2023-12-14 09:24 UTC, kjurenec requested changes
mozda da je scroll unutar border containera?
![CleanShot 2023-12-14 at 10 08 03](https://github.com/ZeroMolecule/screenary/assets/9319312/95b67474-a2e6-4095-a2c8-745e8ddd9f67)

obrisem fb al obrise krivoga
https://github.com/ZeroMolecule/screenary/assets/9319312/bba6e09d-36e4-40eb-8a66-c0d626dfdefa

embeded page treba mijenjati url (biti posebni next page). 
/projects/:projectId/embedded-pages/:page
gledaj jeli ima smisla na refresh izgubiti state ako da ona more useState ako nema smisla da se state izgubi onda ide page ili neki drugi nacin kroz url

2023-12-15 11:38 UTC, kjurenec requested changes

2023-12-15 11:38 UTC, kjurenec commented on packages/web/app/_components/project/embedded-pages/embedded-page-item.tsx
> +      width: Math.min(naturalWidth, ICON_CONTAINER_DIMENSIONS_IN_PIXELS - 1),
nemoremo samo na slici imati maxWidth:100%?

2023-12-15 13:30 UTC, kjurenec requested changes

2023-12-15 13:30 UTC, kjurenec commented on packages/web/app/_components/project/embedded-pages/embedded-page-item.tsx
> +      width: naturalWidth,
mislio sam da je samo max-width (i height auto) dosta. ne treba onLoad uopce?

2023-12-15 13:40 UTC, im-luka commented on packages/web/app/_components/project/embedded-pages/embedded-page-item.tsx
> +      width: naturalWidth,
ali moram na next `<Image />` staviti ili width/height (number) ili `fill` prop. bez tog se nemre koristiti kaj ne? a ako stavim fill onda ništa nisam dobio jer će fillat parenta

2023-12-15 14:01 UTC, kjurenec commented on packages/web/app/_components/project/embedded-pages/embedded-page-item.tsx
> +      width: naturalWidth,
mores koristiti onda obicni img jer tak i tak jer to vanjski url pa next image niti nemoze nikakvu optimizaciju napraviti

2023-12-15 15:58 UTC, im-luka commented on packages/web/app/_components/project/embedded-pages/embedded-page-item.tsx
> +      width: naturalWidth,
a ovako nešto? ovdje koristim mantineov `<Image />` kao polymorphic komponentu gdje odredim da nextov `<Image />` bude korišten:
![image](https://github.com/ZeroMolecule/screenary/assets/46372998/c8ffead2-20e7-4b03-9983-b5aa1a6081eb)

i onda u slučaju da img url faila odnosno da ne postoji, biti će prikazan ovaj placeholder (zadnji link, https://ign.com se raspadne):
<img width="414" alt="Screenshot 2023-12-15 at 16 55 33" src="https://github.com/ZeroMolecule/screenary/assets/46372998/e2af8c93-d25e-41ba-b505-23073eca9f89">

to sam napravio jer ako stavim ovako samo mantineov `<Image />`:
![image](https://github.com/ZeroMolecule/screenary/assets/46372998/0b9aeb57-a91c-41c0-8ee5-5fba51a0cdb0)

onda u ui-u ne bude renderiran fallback, nego bude sve prazno (bijeli background):
<img width="420" alt="Screenshot 2023-12-15 at 16 57 24" src="https://github.com/ZeroMolecule/screenary/assets/46372998/f9c49c3d-497e-42f9-a1ca-06d121aeda5f">

pa mi možeš napisati kaj je po tebi bolje. ovim polymorphic načinom overrideam nextov width i height sa mantineovim ali je rješenje možda malo hacky

2023-12-18 13:31 UTC, im-luka commented
@kjurenec ovo `h="auto"` nije fixalo problem, a zadnji commit je bio s onim width & height pa javi ako ostavljam tako i mogu merge

2023-12-18 14:58 UTC, merged