web/feat: tasks reordering
ZeroMolecule/screenary pull request #37
Opened 2023-12-18 14:15 UTC by im-luka

Tasks/To-Do Reordering

2023-12-18 15:25 UTC, kjurenec requested changes
kad kreiram todo item onda moram rucno refreshati da vidim item.
stavi da todo item label nije text input po defaultu vec text pa onda kad kliknes se pretvori u input s autofocusom. vidi jeli s a11y mores napravi da kazes da je text klikabilni ili neto kao input pa da racunalo zna da nije cisto read only

2023-12-18 15:25 UTC, kjurenec commented on packages/web/app/_components/tasks/tasks-list.tsx
> +    setItems(updatedTasks);
ima ti react-query optimistic update

2023-12-20 08:19 UTC, kjurenec requested changes

2023-12-20 08:19 UTC, kjurenec commented on packages/web/app/_components/tasks/tasks-list.tsx
> +      setItems(tasks ?? []);
joj. nikako nebi trebao setati state kroz useEffect (mislim da smo par puta prosli). napravi da je inicijalno state prazan ili undefined pa na onDragEnd setas state pa nakon sto je akcija gotova clearas da taskovi kroz props preuzmu nakon.
ta naj nacin loklane taskove kroz state tretiras kao snapshot.

umjesto rethrow errora u mutaciji koristi drugi arg (onSettled) da znas clearati taj state

2023-12-20 08:58 UTC, im-luka commented on packages/web/app/_components/tasks/tasks-list.tsx
> +      setItems(tasks ?? []);
znam, i slažem se za useEffect, ali sam probao sve ove načine:
- optimistic update kroz onMutate
- optimistic update unutar onDragEnd funkcije
- praćenje “pending“ statea kroz useMutationState hook i update state u trenutku “pendinga“
- set kroz useRef

i uvijek je isti problem - flash/flick. iduće što mi je ostalo je umjesto react-dnd probati ovaj navodno noviji, moderniji [library za dnd](https://dndkit.com/) jer je problem u react-dndu negdje

prije sam imao ovako:
```ts
import { FC, useState } from 'react';
import { Box } from '@mantine/core';
import {
  DragDropContext,
  Draggable,
  DropResult,
  Droppable,
} from '@hello-pangea/dnd';
import { Task } from '@/domain/queries/tasks-query';
import { Text } from '../base/text';
import { TaskItem } from './task-item';
import { ReorderTaskData } from '@/domain/types/task-data';

type Props = {
  tasks: Task[];
  onEdit: (task: Task) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
  onReorder: (data: Pick<ReorderTaskData, 'data'>) => Promise<void>;
  title?: string;
};

export const TasksList: FC<Props> = (props) => {
  const { title, tasks, onEdit, onDelete, handleOnDragEnd } =
    useTasksList(props);

  const renderTask = (task: Task, index: number) => (
    <Draggable key={task.id} draggableId={task.id} index={index}>
      {({ innerRef, dragHandleProps, draggableProps }) => (
        <div {...dragHandleProps} {...draggableProps} ref={innerRef}>
          <TaskItem task={task} onEdit={onEdit} onDelete={onDelete} />
        </div>
      )}
    </Draggable>
  );

  return (
    <Box>
      <Text size="lg" fw={600}>
        {title}
      </Text>
      <DragDropContext onDragEnd={handleOnDragEnd}>
        <Droppable droppableId="tasks">
          {({ droppableProps, innerRef, placeholder }) => (
            <div {...droppableProps} ref={innerRef}>
              {tasks.map(renderTask)}
              {placeholder}
            </div>
          )}
        </Droppable>
      </DragDropContext>
    </Box>
  );
};

function useTasksList({ title, tasks, onEdit, onDelete, onReorder }: Props) {
  const [items, setItems] = useState(tasks ?? []);

  const handleOnDragEnd = async (result: DropResult) => {
    if (!result.destination) {
      return;
    }

    const orderObject = Object.fromEntries(
      tasks.map((task, index) => [index, task.order])
    );

    const reorderedTasks = [...tasks];
    const [reorderedTask] = reorderedTasks.splice(result.source.index, 1);
    reorderedTasks.splice(result.destination.index, 0, reorderedTask);

    const updatedTasks = reorderedTasks.map((task, index) => ({
      ...task,
      order: orderObject[index],
    }));
    setItems(updatedTasks);

    await onReorder({
      data: updatedTasks.map(({ id, order }) => ({ id, order })),
    }).catch(() => setItems(tasks));
  };

  return { title, tasks: items, onEdit, onDelete, handleOnDragEnd };
}
```

bez useEffecta reordering dobro radi, ali je problem što bez njega inicijalni state bude zapamćen i komponenta se ne updatea kada se promijene podatci liste taskova kroz useQuery izvana:
https://github.com/ZeroMolecule/screenary/assets/46372998/90a2f621-c9bc-4cd4-a517-1f639cfcefcf

zato sam stavio useEffect, to mi je bilo zadnje rješenje, ali sam probao puno drugih prije njega. ali probati ću još ovo što si komentirao

2023-12-20 09:09 UTC, im-luka commented on packages/web/app/_components/tasks/tasks-list.tsx
> +      setItems(tasks ?? []);
nevermind, promaklo mi je valjda najjednostavnije rješenje jer sam pokušavao smisliti neka kompleksnija. ovo što sam sad mergeao handlea automatski i drag&drop state flickering i error handling

2023-12-20 09:34 UTC, kjurenec approved these changes

2023-12-20 10:16 UTC, merged