web/feat: project dashboard layout spacing
ZeroMolecule/screenary pull request #39
Opened 2023-12-19 17:29 UTC by im-luka

Project dashboard layout spacing

[Josh Comment](https://chat.google.com/room/AAAA93IMUyg/axo4EKe_X7g/axo4EKe_X7g?cls=10)
[Figma Design](https://www.figma.com/file/lpIlprAyQ1QAu3O2P7sAm5/Portal-Designs?type=design&node-id=1432-6870&mode=design&t=WmA5UGMOuBIuXGsU-4)

2023-12-20 08:44 UTC, kjurenec requested changes

2023-12-20 08:44 UTC, kjurenec commented on packages/web/_mantine.scss
> +$mantine-breakpoint-2560: rem(2560);
nikad direk tocnu rezoluciju u brekpoint varijabli ne koristis. bolje ti je ici rutom 2xl, 3xl ili xxl, 2xxl...
al mislim da ti niti nece trebati. koliko vidim po figmi na >= 2560 sirina doga desno je 34.9% sirine ekrana (tako nesto) pa onda ne trebao 3 dodatna brekpointa. vjerojano se mogu i druge stvari mogu svesti na "zajednicki nazivnik" jer ovako ima previse rezolucija pa ce kasnije biti konfuzno sve to pratiti. al ako ne ide nista promijeni bar imena breakpointova

2023-12-20 10:16 UTC, im-luka commented
ako imaš ideju ili neko bolje rješenje dapače. jer sam layout napravio da bude u postotcima na ovim velikim ekranima (slično kako sam imao i inicijalno kad sam radio project dashboard - 12 columns - 8-3-1)

kod ovih embedded page itema ne znam kako bih drugačije napravio nego pisao direktno width/height. jer je kod svake veličine ekrana padding između wrappera i stacka drugačiji, padding između itema i stacka drugačiji, width/height svakog itema je drugačiji, plus & placeholder icon width/height je drugačiji. pa ne znam koje bi bilo bolje rješenje bez hardkodiranja vrijednosti width/height za različite ekrane

2023-12-20 11:03 UTC, kjurenec commented
a koliko vidim ovo more ici 22 ili 23%. vidi za ostale.

![CleanShot 2023-12-20 at 12 00 57@2x](https://github.com/ZeroMolecule/screenary/assets/9319312/f26eb11a-9a9c-457a-803e-31aa01a0f45c)

2023-12-20 11:05 UTC, kjurenec commented
> ako imaš ideju ili neko bolje rješenje dapače. jer sam layout napravio da bude u postotcima na ovim velikim ekranima (slično kako sam imao i inicijalno kad sam radio project dashboard - 12 columns - 8-3-1)
> 
> kod ovih embedded page itema ne znam kako bih drugačije napravio nego pisao direktno width/height. jer je kod svake veličine ekrana padding između wrappera i stacka drugačiji, padding između itema i stacka drugačiji, width/height svakog itema je drugačiji, plus & placeholder icon width/height je drugačiji. pa ne znam koje bi bilo bolje rješenje bez hardkodiranja vrijednosti width/height za različite ekrane

nema smisla ici preko grida obzirom da je ovako u postocima custom

2023-12-21 11:35 UTC, kjurenec requested changes

2023-12-21 11:35 UTC, kjurenec commented on packages/web/styles/components/embedded-pages.module.scss
> +  @media (min-width: $mantine-breakpoint-2xl) {
ista stvar je i s ovim pa onda mores maknuti 3xl i 4xl

2023-12-21 14:31 UTC, merged