web/feat: embedded pages reorder
ZeroMolecule/screenary pull request #40
Opened 2023-12-20 13:55 UTC by im-luka

Embedded Pages & Tasks Reordering

2023-12-20 14:19 UTC, kjurenec requested changes
ReorderList je super.

jel more naprviti da item nije nalijepit na drugi prije nego req zavrsi? valjda neki problem sa spacingom
https://github.com/ZeroMolecule/screenary/assets/9319312/bbbbb183-3a26-453e-b19d-d2a6e32a88f2

2023-12-20 14:19 UTC, kjurenec commented on packages/api/src/embedded-pages/embedded-pages.service.ts
> +      await tx.embeddedPage.deleteMany({ where: { id: { in: ids } } });
ovo mora i userId imati u where inace mores obrisati od bilo koga page. nez jel isto i kod taskova pa mi promaklo?

2023-12-21 11:40 UTC, kjurenec requested changes
isto je?
https://github.com/ZeroMolecule/screenary/assets/9319312/cd999991-0d78-4a95-bf92-8fbaa9991d5c

2023-12-21 11:46 UTC, im-luka commented
aha, problem je samo kod zadnjeg elementa, ostalo dobro radi. mislim da znam zašto, pogledam

2023-12-22 07:56 UTC, kjurenec approved these changes

2023-12-22 08:09 UTC, merged