web/feat: project dashboard hide completed tasks button
ZeroMolecule/screenary pull request #46
Opened 2023-12-22 15:10 UTC by im-luka

Project Dashboard - Hide Completed Tasks Option

2024-01-02 09:17 UTC, kjurenec requested changes
nema toggle? moram refresh da bude kak spada.
https://github.com/ZeroMolecule/screenary/assets/9319312/4cea5d23-8e40-4fea-bfeb-e8eb71333f99

nesto key nestima
https://github.com/ZeroMolecule/screenary/assets/9319312/0351a498-b487-40f2-94a9-5316f1fb7eaf

2024-01-09 08:35 UTC, kjurenec requested changes

2024-01-09 08:35 UTC, kjurenec commented on packages/web/app/_components/reorder-list.tsx
> +    <Draggable key={`${item.id}-${index}`} draggableId={item.id} index={index}>
sad se ovo dogada. nisam siguran da je index pametno koristiti kad imas listu koja ima reorder i "delete". id bi trebao biti stabilni bez obzira na akciju. 
treba vidjeti zato se duplicated key javlja pa onda naci neko pametnije rijesenje.

https://github.com/ZeroMolecule/screenary/assets/9319312/4ca866c8-762a-4fd6-bd3a-150d60b39e7e

2024-01-09 10:07 UTC, im-luka commented on packages/web/app/_components/reorder-list.tsx
> +    <Draggable key={`${item.id}-${index}`} draggableId={item.id} index={index}>
ovaj problem nema veze sa tim je li `key={item.id}` ili `key={'${item.id}-${index}'}` (sad sam testirao dev branch i tamo je isto). očito je problem u mixed listi to-do i done itema, a nismo ni ti ni ja skužili kad je bilo na PR-u. pogledati ću i pokušati fixati to sve unutar ovog PR-a, ali ovo pišem pa da se zna u slučaju da mi uzme više vremena

2024-01-09 10:12 UTC, kjurenec commented on packages/web/app/_components/reorder-list.tsx
> +    <Draggable key={`${item.id}-${index}`} draggableId={item.id} index={index}>
dada ovo key nije isto ko i ovo di se pojavi ovo s videa. 2 problema su to al mislim da kad rijes ovo s videa da ce ti se i duplicated key rijesiti jer vjerojatno imas taj key problem jer mergas 2 liste u jednu pa dok se toggla postoji trnutak kad je item i u todo i u done

2024-01-09 10:15 UTC, kjurenec commented on packages/web/app/_components/reorder-list.tsx
> +    <Draggable key={`${item.id}-${index}`} draggableId={item.id} index={index}>
obzirom da je sad sve grupirano mozda nema smisla imati 2 req. jedan za todo jedan za done. vec imati samo jedan req bez filtera pa onda ako user klikne na hide completed se salje opet jedan req ali ovaj put s filterom

2024-01-09 10:32 UTC, im-luka commented on packages/web/app/_components/reorder-list.tsx
> +    <Draggable key={`${item.id}-${index}`} draggableId={item.id} index={index}>
da, u trenutku kad se mijenja status iz TODO-DONE ili obrnuto onda ova mergeana lista na milisekundu ima +1 ili -1 item unutar liste (ovisi o iz kojeg u koji status ide) - npr. umjesto 12 itema ima 11 ili 13. ali sam i krenuo ovako kako si i napisao, da u ovom slučaju šaljem jedan req

2024-01-10 12:13 UTC, kjurenec requested changes

2024-01-10 12:13 UTC, kjurenec commented on packages/web/hooks/use-tasks.ts
> +        enabled: !config?.includeAllResults,
hmm. ovo bi sad trebao biti jedan query / jedan request. samo mjenjas key.

2024-01-10 17:20 UTC, kjurenec commented on packages/web/hooks/use-tasks.ts
> +        enabled: !config?.includeAllResults,
da znaci samo je jedan query i defaultno key nema nista kao key znaci dohvacas sve (nema lokalno filtriranje status). i onda kad user stisne na hide completed onda taj key prima status.
nista drugacije nego da radis tablicu koja ima filtere. recimo estatesales. imas tablicu aukcija a iznad filter za statuse a isti je query uvijek

2024-01-12 07:57 UTC, kjurenec requested changes

2024-01-12 07:57 UTC, kjurenec approved these changes

2024-01-12 08:07 UTC, merged