web/feat: sentry setup (front & back)
ZeroMolecule/screenary pull request #6
Opened 2023-10-26 17:42 UTC by im-luka

[SCREEN - 19 ➡️ Enable Crash Reporting](https://zeromolecule.atlassian.net/browse/SCREEN-19?atlOrigin=eyJpIjoiZjA4MTRiYzRjNzFjNDlmYzk2YjU1N2JkY2FhYWM4YmIiLCJwIjoiaiJ9)
- [[Frontend] Integrate Sentry](https://zeromolecule.atlassian.net/browse/SCREEN-30?atlOrigin=eyJpIjoiMTk4MmViM2VjZDcxNDNmNWEyZDU1NTQ5NTk3MjRjZmIiLCJwIjoiaiJ9)
- [[Backend] Integrate Sentry](https://zeromolecule.atlassian.net/browse/SCREEN-29?atlOrigin=eyJpIjoiZWI0OTAxYWJhZGY0NDM5NjljYWFiNTQ2MDMwNGYwNjAiLCJwIjoiaiJ9)

i front i back sentry logging radi isključivo u produkciji, ispod ću napisati rute na kojima možeš testirati. što se tiče stack tracea - na frontu dobro radi i dobro ispisuje (stavi snippet koda), na backu nisam uspio nikako napraviti da radi. nema što nisam probao, custom webpack setup, custom typescript setup, dupli library (jedan za front, jedan za back), nekoliko libraryja (jedan od njih je [travelerdev/nestjs-sentry](https://www.npmjs.com/package/%40travelerdev%2Fnestjs-sentry) koji bi navodno trebao biti upgradeani [ntegral/nestjs-sentry](https://www.npmjs.com/package/@ntegral/nestjs-sentry)). imam puno ostalih taskova tako da trenutno nemam vremena više za ovo, kad ostale taskove završim mogu se vratiti, a do tada stavljam na pr jer ćeš ti možda skužiti u čemu je problem kad ćeš prolaziti kod a da ja nisam skužio

`/client` 👉🏼 ruta za tesitranje client errora  
`/server` 👉🏼 ruta za tesitranje web servera  
`/backend` 👉🏼 ruta za tesitranje api backenda

2023-10-30 09:57 UTC, kjurenec requested changes

2023-10-30 15:18 UTC, im-luka commented on packages/web/sentry.edge.config.ts
> +import * as Sentry from '@sentry/nextjs';
da i pretpostavljam da da. u docsima je i ovaj file pa sam ga zato i ja koristio. iako i bez njega error report radi, ali ga nisam htio obrisat za svaki slučaj. da ga maknem onda ili ne?

2023-10-31 08:39 UTC, kjurenec commented on packages/web/sentry.edge.config.ts
> +import * as Sentry from '@sentry/nextjs';
ma ostavi ga

2023-10-31 08:41 UTC, kjurenec commented on packages/web/sentry.edge.config.ts
> +import packageJSON from '../../package.json';
mozda bi ovo bilo bolji nacin dohvacanja verzije? 
`process.env.npm_package_version`
nekak mi je cudno direkt importati package.json

2023-10-31 09:02 UTC, merged