web/feat: auth UI and social login
ZeroMolecule/screenary pull request #9
Opened 2023-11-02 10:38 UTC by im-luka

### [SCREEN - 2 ➡️ AUTHENTICATION](https://zeromolecule.atlassian.net/browse/SCREEN-2?atlOrigin=eyJpIjoiMjRiODg2MDMwZTIyNDhmYmFlZmIyNjVmNjMzZDViMTYiLCJwIjoiaiJ9)

- [SCREEN - 39 ➡️ Create Authentication Screen and Handle Routing](https://zeromolecule.atlassian.net/browse/SCREEN-39?atlOrigin=eyJpIjoiOTZkMTBiMWVjMDBjNDI1Nzg2NmQ0NzE3OGVjODEyZjAiLCJwIjoiaiJ9)
- - [Implement General Authentication Screen and Routing](https://zeromolecule.atlassian.net/browse/SCREEN-41?atlOrigin=eyJpIjoiZDZiZGNmZGE5OGQ0NDVkN2JkZWMyYjY3MzkxZGM5MWEiLCJwIjoiaiJ9)

- [SCREEN - 37 ➡️ Implement Google Sign-in](https://zeromolecule.atlassian.net/browse/SCREEN-37?atlOrigin=eyJpIjoiOTFiM2RlZTMxMTNjNDcxNmIxMmNmMDU2MmEwOTU3NTEiLCJwIjoiaiJ9)
- - [Implement Google Sign-In Button](https://zeromolecule.atlassian.net/browse/SCREEN-42?atlOrigin=eyJpIjoiNjEyYzhjZmI2NDRiNGE5ZGI3MmJiYTRjZDAwZDY4NjYiLCJwIjoiaiJ9)

- [SCREEN - 43 ➡️ Implement Apple Sign-In](https://zeromolecule.atlassian.net/browse/SCREEN-43?atlOrigin=eyJpIjoiNzFjYTk3Zjk4OThlNDZmZjkyNThiMDFjMmM4N2QzMjAiLCJwIjoiaiJ9)
- - [Implement Apple Sign-In Button](https://zeromolecule.atlassian.net/browse/SCREEN-45?atlOrigin=eyJpIjoiNTQ5OTIxZGYwODVmNDk2NGJlNTY1NjNhZjVkODIyYTIiLCJwIjoiaiJ9)

- [SCREEN - 46 ➡️ Implement Facebook Sign-In](https://zeromolecule.atlassian.net/browse/SCREEN-46?atlOrigin=eyJpIjoiOWNmYWU0OGRmNjkxNGU3Yjg2MzJlNDUxNjU3ZDNiYTQiLCJwIjoiaiJ9)
- - [Implement Facebook Sign-In Button](https://zeromolecule.atlassian.net/browse/SCREEN-48?atlOrigin=eyJpIjoiY2UxMzIwOTNlODdjNDQzZGEwMzZiYzVmZThmNDYzMGUiLCJwIjoiaiJ9)

---

### [SCREEN - 2 ➡️ USER MANAGEMENT](https://zeromolecule.atlassian.net/browse/SCREEN-3?atlOrigin=eyJpIjoiZGMwOWNjYmZiN2I2NGU0OGEzYzhjZDhjNTUwMzMwNzQiLCJwIjoiaiJ9)

- [SCREEN - 56 ➡️ Signing Out](https://zeromolecule.atlassian.net/browse/SCREEN-56?atlOrigin=eyJpIjoiNDNhNTA5YmU5MGQ3NDY2NTk1ODljM2E1MDAxN2UwODQiLCJwIjoiaiJ9)  
- - [Implement Sign Out Button](https://zeromolecule.atlassian.net/browse/SCREEN-58?atlOrigin=eyJpIjoiOTM2M2I0MzU2ZjlkNDMwNmFkNWFiMmQ3MTQ2OGE4NDkiLCJwIjoiaiJ9)

---

`/client` 👉🏼 ruta za tesitranje client tokena  
`/server` 👉🏼 ruta za tesitranje server tokena

2023-11-02 16:04 UTC, kjurenec requested changes

2023-11-02 16:04 UTC, kjurenec commented on packages/web/domain/db/prisma-client.ts
> +const globalForPrisma = globalThis as unknown as {
kuzim da je ovo s prisme doca al jel nam treba global ako vec imamo dole export i koristimo taj export zapravo kod adaptera. mislim da opcenito nije dobar best practice kad se moduli koriste da se "zagaduje" global

2023-11-02 16:04 UTC, kjurenec commented on packages/web/styles/components/container.css
> +  overflow: scroll;
nisam siguran da je ovo ikad dobra ideja. 

![CleanShot 2023-11-02 at 17 02 27](https://github.com/ZeroMolecule/screenary/assets/9319312/dcd682bc-c060-4d9d-ad60-7b4518135778)

2023-11-02 16:04 UTC, kjurenec commented on packages/web/styles/components/container.css
> +  max-width: rem(1440);
rekao bi da je width tog crnog bg full width - padding 32px s jedne i druge strane

2023-11-03 12:06 UTC, im-luka commented on package.json
> +    "classnames": "^2.3.2",
koliko sam gledao, `cx` su maknuli u `v7`. na docsima evenutalno koriste `clsx` za mergeanje više klasa skupa:
<img width="587" alt="Screenshot 2023-11-03 at 13 04 17" src="https://github.com/ZeroMolecule/screenary/assets/46372998/9bcb80a5-7b75-48c5-ab7d-763c2dd54423">

mogu zamijeniti `classnames` za `clsx` ako je bolje to koristiti

2023-11-03 12:37 UTC, kjurenec commented on package.json
> +    "classnames": "^2.3.2",
neka ostane vidim da i jedan i drugi imaju 12m downloada

2023-11-03 12:49 UTC, im-luka commented on packages/web/styles/components/social-button.css
> +    color: var(--mantine-color-white);
nije bolje da ostane ovako kroz modifier s obzirom da componenta funkcionira tako da joj se proslijedi samo string providera? jer inače ću morati i za `bg` i za `color` prop imati funkciju koja će dodijeliti boju ovisno o provideru kroz kod, a ovako se css pobrine za to. plus svakako ću morati imati `--google` modifier klasu jer u tom slučaju moram staviti i border

2023-11-03 12:52 UTC, im-luka commented on packages/web/styles/components/social-button.css
> +    gap: var(--mantine-spacing-md);
nisam to htio stavljati jer mi se čini da je spacing između teksta i ikone u ovom slučaju specifičniji (veći), a da je u drugim primjerima manji. pa mi se činilo da je ovo specifična, a ne 'base' verzija. ali mogu promijeniti ako misliš da je bolje

2023-11-03 14:34 UTC, im-luka commented on packages/web/domain/db/prisma-client.ts
> +const globalForPrisma = globalThis as unknown as {
da u official [prisma docsima](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices) i [vercel guideu za next.js i prismu](https://vercel.com/guides/nextjs-prisma-postgres) se ide ovim načinom preko globala pa sam zato to koristio. mislio sam da je svakako bolje to nego na svaki request stvarati novu prisma client instancu

kaj bi ti predložio? jel dosta napisati samo `export const prismaClient = new PrismaClient();` s obzirom da na frontu prismu koristimo samo zbog next-auth adaptera, a zapravo sve operacije idu preko backa?

2023-11-03 14:34 UTC, im-luka commented on packages/web/styles/components/container.css
> +  max-width: rem(1440);
kako si došao do ove kalkulacije? nisam baš skužio

2023-11-03 14:37 UTC, im-luka commented on packages/web/domain/remote/index.ts
> +    const session = await getSession();
možeš malo ovo objasniti jer nisam skužio zašto je to tako? htio sam setupirati istu axios instancu za koristiti na clientu i serveru i ovo je bio jedini način kojim sam uspio to postići. koji bi bio bolji način?

2023-11-03 14:39 UTC, im-luka commented
@kjurenec većinu stvari sam fixao, a ostavio sam i nekoliko komentara pa ću to fixati kad mi odgovoriš

2023-11-03 14:54 UTC, kjurenec commented on packages/web/styles/components/container.css
> +  max-width: rem(1440);
crni bg (onaj s borderom) nema max width vec ide koliko ima sirine uz 32 px margine/padding (ovisi kak napravis)

2023-11-03 14:56 UTC, kjurenec commented on packages/web/domain/db/prisma-client.ts
> +const globalForPrisma = globalThis as unknown as {
dada to je ok. global samo makni jer nema smisla imati i jedno i drugo pogotovo kad s modulima radis.
zelis da je modul izlorian a ne da mutira okolo stvari

2023-11-03 14:59 UTC, kjurenec commented on packages/web/domain/remote/index.ts
> +    const session = await getSession();
si otvorio network tab kad saljes req na /users/me ?
vidjet ces da se prvo salje req na session a tek onda na /users/me i to radis za svaki req. 
onda imas primjer di imas recimo 3 razlicita useQuerija na pageu i onda umjesto 3 req se salju 6. a nije da ce se session promijeniti u toj sekundi

2023-11-03 15:00 UTC, kjurenec commented
> @kjurenec većinu stvari sam fixao, a ostavio sam i nekoliko komentara pa ću to fixati kad mi odgovoriš

@im-luka odgovorih ti

2023-11-03 16:15 UTC, kjurenec commented on packages/web/styles/components/social-button.css
> +    color: var(--mantine-color-white);
pa samo ces prebaciti logiku iz css u komponentu.
pricam zato sto mi ima vise smisla iskoristiti mogucnosti ui liba nego raditi rucno

2023-11-03 16:18 UTC, kjurenec commented on packages/web/styles/components/social-button.css
> +    gap: var(--mantine-spacing-md);
imas primjer takvog buttona?

2023-11-06 07:30 UTC, im-luka commented on packages/web/styles/components/social-button.css
> +    gap: var(--mantine-spacing-md);
<img width="451" alt="Screenshot 2023-11-06 at 08 26 37" src="https://github.com/ZeroMolecule/screenary/assets/46372998/5939f544-878e-4fa9-b7c7-5090d5e01712">
<img width="488" alt="Screenshot 2023-11-06 at 08 27 41" src="https://github.com/ZeroMolecule/screenary/assets/46372998/c1883a54-540f-4c4f-85a6-d280f2f1516a">
<br />
<img width="172" alt="Screenshot 2023-11-06 at 08 28 52" src="https://github.com/ZeroMolecule/screenary/assets/46372998/77904c37-6404-48bf-a446-5d61d7e9cfa6">

2023-11-06 08:06 UTC, kjurenec requested changes

2023-11-06 08:10 UTC, kjurenec commented on packages/web/styles/components/social-button.css
> +    gap: var(--mantine-spacing-md);
je to button koji bi trebao u temi imati isti size?

2023-11-06 08:16 UTC, im-luka commented on packages/web/domain/remote/index.ts
> +    const session = await getSession();
iskreno nisam te ni tada najbolje shvatio na kaj si točno mislio i kako bi to zapravo istovremeno moglo handleati i server i client fetchanje podataka

a ovaj način? kada se koristi `remoteApi` axios instanca, samo će prvi fetch ići na session i tada nadalje će se shareati token koji se tada dohvati. sve dok je user ulogiran:
![image](https://github.com/ZeroMolecule/screenary/assets/46372998/de28f7e7-4506-4793-acdc-30d671ebc3aa)

2023-11-06 09:08 UTC, kjurenec commented on packages/web/domain/remote/index.ts
> +    const session = await getSession();
za sad more biti kako nekakva logika ali probaj postali 2-3 requesta istovremeno

2023-11-06 09:11 UTC, kjurenec commented on packages/web/domain/remote/index.ts
> +    const session = await getSession();
inicijalno 2-3 req mislim. znci simuliras ono sto ce se u stvaronosti desiti kad prvi put dodes na page pa se okinu svi potrebni useQuery-ji

2023-11-06 09:12 UTC, kjurenec commented on packages/web/domain/remote/index.ts
> +    const session = await getSession();
sad inace imas prazni varijabu (token) na serveru koja nicemu sluzi. al malo se oduzio auth pa neka bude tak :)

2023-11-07 08:22 UTC, kjurenec approved these changes

2023-11-07 08:22 UTC, kjurenec commented on packages/web/app/_hoc/with-private-page.tsx
> +export const withPrivatePage = (Component: FC<Props>) => {
nameing je malo cudan al ok

2023-11-07 12:31 UTC, merged